### PR TITLE
Add .rustfmt.toml and .editorconfig

### PR DESCRIPTION
**Pull request by stevenroose**
Makes it a lot easier for contributes to avoid accidentally introducing random changes.

### CODE REVIEW

**Comment by apoelstra** [comment]
We are not using rustfmt before 1.0 and we are *definitely* not overriding the tab settings to disagree with every other rust-bitcoin project and the wider Rust community for 4 years.

**Comment by stevenroose** [comment]
https://github.com/rust-bitcoin/rust-lightning

> Notes on coding style:
> 
>  - Use tabs. If you want to align lines, use spaces. Any desired alignment should display fine at any tab-length display setting.

Whoops. Fair enough. Can change to spaces. It's just really annoying to have to worry about code formatting while programming. It's a delight to be able to ignore format-related typos and have them corrected on `:w` ;)

**Comment by apoelstra** [comment]
Heh, fair enough. In fairness please do not copy Matt's format style to any other projects ;)

**Comment by apoelstra** [comment]
While you're at it can you add a commit that replaces `try!` with `?`? Can rustfmt enforce that?

**Comment by stevenroose** [comment]
I could, but fwiw that block gets removed in #20 and isn't really in the scope of this change. rustfmt doesn't do that. Not sure why. I guess it should only do formatting.

**Comment by apoelstra** [comment]
Ok, sgtm

**Pull request merged**
