### PR TITLE
version bump and small cleanups

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Comment by apoelstra** [comment]
lol we'll have to hold off on this a bit and figure out something much more ergonomic for passing arguments than using `Box<RawValue>`s...these are very annoying to produce from anything except json strings.

**Review by darosior — APPROVED** [review]
Tested ACK f615f67

**Comment by stevenroose** [comment]
Can you rebase this?

**Comment by darosior** [comment]
@stevenroose looks like it is already?

**Comment by stevenroose** [comment]
Oh I didn't see the 19hrs ago update.

**Review by stevenroose — APPROVED** [review]
Cool!

**Comment by apoelstra** [comment]
Was able to successfully sync the chain and find all my UTXOs using this. Was a bit slow but RPC was not the bottleneck. Haven't yet tested with Liquid but I'm happy with the API and perf improvements can go in point releases (as can, e.g. a new simple-http which uses async and is smarter about sleeping).

**Pull request merged**
