### PR TITLE
Bump version to 0.17.0

### LINKED ISSUE #110: 0.17.0 Release
Is it possible to have the 0.17.0 release?

I have client code using https://github.com/apoelstra/rust-jsonrpc/pull/108

### PR DESCRIPTION
**Pull request by RCasatta**
changelog was already good (just fixed the date)

close #110

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK 9a7c549f2035e183e9f908baa2725d583490ac69

**Comment by apoelstra** [comment]
Looks like CI is probably broken because both `log` and `backtrace` have recently broken MSRV. I will go ahead and merge this, but just noting it for now. Probably we should bump our MSRV from 1.48 to 1.56.1 anyway and then re-audit our dependency pins.

**Review by apoelstra — APPROVED** [review]
ACK 9a7c549f2035e183e9f908baa2725d583490ac69

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
