### PR TITLE
bump version 0.17.0 -> 0.18.0

### PR DESCRIPTION
**Pull request by RCasatta**
I have been bitten again by this, better to release please :)

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK e2d3660ee4378669b302ac34da64a699f5cbe41f

**Review by tcharding — APPROVED** [review]
ACK e2d3660ee4378669b302ac34da64a699f5cbe41f

**Comment by tcharding** [comment]
Out of interest, what bit you @RCasatta? (I see `bitcoincore-rpc` is using `jsonrpc v0.14.0`.)

**Comment by apoelstra** [comment]
Tagged and published.

**Comment by RCasatta** [comment]
> Out of interest, what bit you @RCasatta? (I see bitcoincore-rpc is using jsonrpc v0.14.0.)

Bitcoin core never replies with chunked encoding, however, we are using this lib in lwk https://github.com/Blockstream/lwk with tinyhttp as server.
If the content is big enough tinyhttp use chunked encoding, and the simplehttp client fails with unclear errors.
Using minreq-based transport fixes this

**Pull request merged**
