### PR TITLE
add MSRV details to README

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by stevenroose** [comment]
I'm getting an error on the last command for v1.22:

```
$ rustup run 1.22.0  cargo update -p 'log:0.4.11' --precise '0.4.8'
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `= 0.3.9` found for package `log` (required by `hyper`)
location searched: registry https://github.com/rust-lang/crates.io-index
versions found: 0.4.8
```

While doing that same `cargo update` using stable works. But I assume users with 1.22 can't just use stable to apply their cargo updates..

**Comment by apoelstra** [comment]
That line is frustratingly fragile. Unless you have `0.4.11` installed it just won't work, but I can't figure out how to make it more general.

My guess is that it isn't actually needed for 1.22?

**Comment by apoelstra** [comment]
Let's just bump the MSRV to 1.29 so we can drop this line.

**Comment by apoelstra** [comment]
@stevenroose how about now?

**Comment by apoelstra** [comment]
Needs update in light of #20 (should match the contrib/test.sh commands from #34)

**Review by stevenroose — APPROVED** [review]

**Pull request merged**
