### PR TITLE
A few fixes to the simple_http transport

### PR DESCRIPTION
**Pull request by darosior**
~~There is still the `Content-length` header that we don't set but i don't have a nice fix..~~

### CODE REVIEW

**Comment by darosior** [comment]
I can remove d8add2a5c4678141798edf24ee36bad941953174 if we don't want it, was really just to not pollute other commits with my editor's `rustfmt` hook..

**Comment by darosior** [comment]
Still have a few crash testing this (but at least i can talk to bitcoind!), investigating..

**Comment by darosior** [comment]
Alright, i think it's working as previously now. Going to run on it downstream for testing..

**Review by apoelstra — APPROVED** [review]
ack 80223c3734c5457184c5f0c385e7d3753ca9d024

**Comment by apoelstra** [comment]
Was this entirely pulled into #39?

**Comment by darosior** [comment]
I think so, closing

**Pull request closed without merging**
