### PR TITLE
Null result

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by dpc** [comment]
@stevenroose It's not like this library will generate the second version. It's just that it will accept it as "success" (since it doesn't have `error` field anyway). It the sender that is at fault, and we will just go along and consider it "success", because we can't easily know if it was first or second version at serde level. There's nothing in the spec that says receiver must handle misbehaving sender one way or another, so technically we're good. And without this change some some Bitcoin RPCs are just not working (`invalidateblock`), so we have to do something.

**Comment by stevenroose** [comment]
`invalidateblock` returns no result? *sigh* 

Yeah there is a lot of calls in it's API that should produce empty results.

**Comment by dpc** [comment]
I forgot to link to the issue: https://github.com/apoelstra/rust-jsonrpc/issues/15

**Comment by apoelstra** [comment]
Needs rebase. But concept ACK -- I agree this is kinda inelegant but that's the nature of jsonrpc.

**Comment by dpc** [comment]
Done

**Comment by dpc** [comment]
Hello? :)

**Pull request merged**
